invoice/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^$', views.List, name='InvoiceList'),
    url(r'^edit/', views.Edit, name='InvoiceEdit'),
    url(r'^add/', views.Add, name='InvoiceAdd'),
    url(r'^delete/', views.Delete, name='InvoiceDel'),
    url(r'^view/', views.View, name='InvoiceView'),
    url(r'^paid/', views.SetDateOfPayment, name='InvoiceSetDate'),
)

sig/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('index.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^invoice/', include('invoice.urls')),
    url(r'^article/', include('article.urls')),
	url(r'^register/', include('register.urls')),
    url(r'^contractor/', include('contractor.urls')),
)

invoice/models.py
from django.db import models
from django import forms

class ArticleGatherer(models.Model):
    Invoice=models.ForeignKey('Invoice')
    Article=models.ForeignKey('article.Article')
    Quantity=models.PositiveSmallIntegerField(default=1)

class Invoice(models.Model):
    Contractor=models.ForeignKey('contractor.Contractor')
    Articles=models.ManyToManyField('article.Article', through='ArticleGatherer')
    DateOfSale=models.DateField(auto_now_add=True)
    PAYMENT_CHOICES=(
        ('CASH', 'Cash'),
        ('TRANSFER', 'Transfer'),
    )
    MethodOfPayment=models.CharField(max_length=8, choices=PAYMENT_CHOICES, default='CASH')
    DateOfPayment=models.DateField(null=True)

    def __unicode__(self):
        out=self.Contractor.Name+' '+str(self.DateOfSale)
        out=out+'\n'+self.MethodOfPayment+str(self.DateOfPayment)
        return out
from article.models import Article

class ArticleGathererForm(forms.ModelForm):
    Quantity=forms.IntegerField(widget=forms.NumberInput(attrs={'min':'1'}), initial=1)
    class Meta:
        model=ArticleGatherer
        exclude=['Invoice']

class InvoiceForm(forms.ModelForm):
    NumberOfArticles=forms.IntegerField(widget=forms.HiddenInput(), initial=1)
    class Meta:
        model=Invoice
        exclude=['Articles', 'DateOfPayment']

invoice/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render, redirect
from django.utils import timezone

from models import *
from register.models import UserType

def List(request):        
    usertype = UserType.objects.get(name=request.user.username)
    
    if usertype.isWorker:
        invoices=Invoice.objects.all()
    else:
        contractors=Contractor.objects.filter(Login=usertype)
        invoices=[]
        for contractor in contractors:
            invoices.extend(Invoice.objects.filter(Contractor=contractor))
    
    context={'Invoices' : invoices, 'isWorker':usertype.isWorker}
    return render(request, 'invoice_list.html',context)

def View(request):
    if request.method == 'POST':
        invoice=Invoice.objects.get(id=request.POST['id'])
        articles=ArticleGatherer.objects.filter(Invoice=invoice)
        context={'Invoice' : invoice, 'ArticleGatherers' : articles}
        return render(request, 'invoice_view.html', context)
        
    return redirect('invoice.views.List')

def SetDateOfPayment(request):
    if request.method == 'POST':
        invoice=Invoice.objects.get(pk=request.POST['id'])
        invoice.DateOfPayment=timezone.localtime(timezone.now()).date()
        invoice.save()
    return redirect('invoice.views.List')

def Edit(request):
    usertype = UserType.objects.get(name=request.user.username)
    isWorker = usertype.isWorker 
    
    articleGathererFormExample=ArticleGathererForm(prefix='article___NUMBER__')
    articleGathererForms=[]
        
    if request.method == 'POST':
        invoice=Invoice.objects.get(id=request.POST['id'])
        invoiceForm = InvoiceForm(request.POST, prefix='invoice', instance=invoice) # powiązanie formularza z przesłanymi danymi
        if invoiceForm.is_valid():
            data = invoiceForm.cleaned_data
            invoice=invoiceForm.save(commit=False)
            for i in range(data['NumberOfArticles']):
                articleGathererForm=ArticleGathererForm(request.POST, prefix='article_'+str(i+1))
                articleGathererForms.append(articleGathererForm)

            for articleGathererForm in articleGathererForms:
                if not articleGathererForm.is_valid():
                    context={'InvoiceForm':invoiceForm, 'ArticleGathererForms' : articleGathererForms, 'ArticleGathererFormExample' : articleGathererFormExample, 'isWorker':isWorker}
                    return render(request, 'invoice_add.html', context)
                
           
                               
            #skoro przeszło wszystkie artykuły i jest ok, to można zapisać, ale tylko jeśli są jakieś artykuły!
            if articleGathererForms:
                invoice.save()
                for articleGathererForm in articleGathererForms:
                    articleGatherer=articleGathererForm.save(commit=False)
                    articleGatherer.Invoice=invoice
                    articleGathererForm.save()
					
            return redirect('invoice.views.List')

    else:
        if request.GET.get('id'):
            invoice=Invoice.objects.filter(pk=request.GET['id'])
            if invoice:
                invoice=invoice[0]
                i=1
                for article in ArticleGatherer.objects.filter(Invoice=invoice):
                    articleGathererForms.append(ArticleGathererForm(instance=article, prefix='article_'+str(i)))
                    i=i+1
                if isWorker and invoice.DateOfPayment == None:
                    invoiceForm=InvoiceForm(instance=invoice, prefix='invoice', initial={'NumberOfArticles':len(articleGathererForms)})
                elif invoice.Contractor.Login==usertype and invoice.Contractor.Supplier==False and invoice.DateOfPayment == None:
                    invoiceForm=InvoiceForm(instance=invoice, prefix='invoice', initial={'NumberOfArticles':len(articleGathererForms)})
                else:
                    return redirect('invoice.views.List')
            else:
                return redirect('invoice.views.List')
        else:
            return redirect('invoice.views.List')
    
    context={'InvoiceForm':invoiceForm, 'ArticleGathererForms': articleGathererForms, 'ArticleGathererFormExample' : articleGathererFormExample}
    return render(request, 'invoice_edit.html', context)

from article.models import Article
from contractor.models import Contractor

def Add(request):
    usertype = UserType.objects.get(name=request.user.username)
    isWorker = usertype.isWorker

    articleGathererFormExample=ArticleGathererForm(prefix='article___NUMBER__')
    articleGathererFormExample.fields['Article'].queryset = Article.objects.filter(Availability=True)
    articleGathererForms=[]
    
    if request.method == 'POST': # formularz został przesłany
        invoiceForm = InvoiceForm(request.POST, prefix='invoice') # powiązanie formularza z przesłanymi danymi
        if invoiceForm.is_valid():
            data = invoiceForm.cleaned_data
            invoice=invoiceForm.save(commit=False)
            for i in range(data['NumberOfArticles']):
                articleGathererForm=ArticleGathererForm(request.POST, prefix='article_'+str(i+1))
                articleGathererForms.append(articleGathererForm)
                
            for articleGathererForm in articleGathererForms:
                if  not articleGathererForm.is_valid():
                    context={'InvoiceForm':invoiceForm, 'ArticleGathererForms' : articleGathererForms, 'ArticleGathererFormExample' : articleGathererFormExample, 'isWorker':isWorker}
                    return render(request, 'invoice_add.html', context)
                
            if articleGathererForms:
                invoice.save()
                for articleGathererForm in articleGathererForms:
                    articleGatherer=articleGathererForm.save(commit=False)
                    articleGatherer.Invoice=invoice
                    articleGathererForm.save()
					
            return redirect('invoice.views.List')

        else:

            for i in range(int(invoiceForm.hidden_fields()[0].value())):
                    articleGathererForms.append(ArticleGathererForm(request.POST, prefix='article_'+str(i+1)))
    else:
        invoiceForm = InvoiceForm(prefix='invoice')
        if isWorker:
            invoiceForm.fields['Contractor'].queryset = Contractor.objects.filter()
        else:
            invoiceForm.fields['Contractor'].queryset = Contractor.objects.filter(Login=usertype, Supplier=False)

        articleGathererForm=ArticleGathererForm(prefix='article_1')
        if not isWorker:
          articleGathererForm.fields['Article'].queryset = Article.objects.filter(Availability=True)

        articleGathererForms=[articleGathererForm] 
           
    context={'InvoiceForm':invoiceForm, 'ArticleGathererForms' : articleGathererForms, 'ArticleGathererFormExample' : articleGathererFormExample, 'isWorker':isWorker}
    return render(request, 'invoice_add.html', context)

def Delete(request):
    if request.GET.get('id'):
        usertype = UserType.objects.get(name=request.user.username)
        invoice=Invoice.objects.filter(id=request.GET['id'])
        if invoice:
            invoice=invoice[0]
            if usertype.isWorker:
                invoice.delete()
            elif invoice.Contractor.Login==usertype and invoice.Contractor.Supplier==False and (invoice.DateOfPayment == None):
                invoice.delete()
    return redirect('invoice.views.List')

invoice/templates/invoice_add.html
{% load staticfiles %}

<script src="{% static 'js/addArticleToInvoice.js' %}" language="Javascript" type="text/javascript"></script>

<div id="example" style="display:none;">
  {{ ArticleGathererFormExample.as_p }}
</div>

{% include "menu.html" %}

<div class="jumbotron">
  <div class="container">
    <h3>Add Invoice: </h3>
    {% if InvoiceForm.errors %}
    <p style="color: red;">There were errors: </p>
    {% endif %}

    <form action="" method="POST" name="invoice">
      {% csrf_token %}
      {{ InvoiceForm.as_p }}
      <input type="button" value="Add article" class="btn btn-default" onClick="addArticleToInvoice('articleDiv', '{{ InvoiceForm.prefix  }}');">
      <input type="button" value="Delete last article" class="btn btn-default" onClick="delArticleFromInvoice('articleDiv', '{{ InvoiceForm.prefix  }}');">
      <div id="articleDiv">
        {% for ArticleGathererForm in ArticleGathererForms %}
        <div id="{{ ArticleGathererForm.prefix }}-div">
          {{ ArticleGathererForm.as_p }}
        </div>
        {% endfor %}
      </div>
      <input type="submit" value="Add" class="btn btn-default" />
    </form>
  </div>
</div>

invoice/templates/invoice_edit.html
{% load staticfiles %}

<script src="{% static 'js/addArticleToInvoice.js' %}" language="Javascript" type="text/javascript"></script>

<div id="example" style="display:none;">
  {{ ArticleGathererFormExample.as_p }}
</div>

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

{% include "menu.html" %}

<div class="jumbotron">
  <div class="container">
    <h3>Edit Invoice: </h3>
    {% if InvoiceForm.errors %}
    <p style="color: red;">There were errors: </p>
    {% endif %}

    <form action="" method="POST">
      {% csrf_token %}
      <input type="hidden" name="id" value="{{ InvoiceForm.instance.id }}" />
      {{ InvoiceForm.as_p }}
      <input type="button" value="Add article" class="btn btn-default" onClick="addArticleToInvoice('articlesDiv', '{{ InvoiceForm.prefix  }}');">
      <input type="button" value="Delete last article" class="btn btn-default" onClick="delArticleFromInvoice('articlesDiv', '{{ InvoiceForm.prefix  }}');">

      <div id="articlesDiv">
        {% for ArticleGathererForm in ArticleGathererForms %}
        <div id="{{ ArticleGathererForm.prefix }}">
          {{ ArticleGathererForm.as_p }}
        </div>
        {% endfor %}
      </div>

      <input type="submit" value="Save" class="btn btn-default" />
    </form>
  </div>
</div>

invoice/templates/invoice_list.html
{% load staticfiles %}


{% include "menu.html" %}
<div class="jumbotron">
  <div class="container">
    {{ info }}
    <h2>Invoices: </h2>
    <div class="row">
      <div class="col-md-2">
        <h3>Contractor</h3>
      </div>
      <div class="col-md-2">
        <h3>Date of Sale</h3>
      </div>
      <div class="col-md-3">
        <h3>Method of Payment</h3>
      </div>
      <div class="col-md-2">
        <h3>Date of Payment</h3>
      </div>
    </div>
  </div>
</div>
{% for Invoice in Invoices %}
{% if forloop.counter|divisibleby:2 %}
<div class="jumbotron">
  {% endif %}
  <div class="container">
    <div class="row">
      {% if not forloop.counter|divisibleby:2 %}
      <b>
	{% endif %}
        <div class="col-md-2">
          <p>{{ Invoice.Contractor }}</p>
        </div>
        <div class="col-md-2">
          <p>{{ Invoice.DateOfSale }}</p>
        </div>
        <div class="col-md-3">
          <p>{{ Invoice.get_MethodOfPayment_display }}</p>
        </div>
        <div class="col-md-2">
          <p>{{ Invoice.DateOfPayment }}</p>
        </div>
	{% if not forloop.counter|divisibleby:2 %}
      </b>
      {% endif %}
      <div class="col-md-2">
      {% if isWorker %}
      <div class="col-md-4">
        <form action="{% url 'InvoiceSetDate'  %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ Invoice.id }}" />
            <input type="submit" value="Paid" class="btn btn-default"  />
          </form>
        </div>
      {% endif %}
        <div class="col-md-4">
          <form action="{% url 'InvoiceView'  %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ Invoice.id }}" />
            <input type="submit" value="View" class="btn btn-default"  />
          </form>
        </div>
        {% if not Invoice.DateOfPayment %}
	<div class="col-md-4">
          <form action="{% url 'InvoiceEdit'  %}" method="GET">
            <input type="hidden" name="id" value="{{ Invoice.id }}" />
            <input type="submit" value="Edit" class="btn btn-default"  />
          </form>
        </div>
        {% endif %}
        <div class="col-md-4">
          <form action="{% url 'InvoiceDel' %}" method="GET">
            <input type="hidden" name="id" value="{{ Invoice.id }}" />
            <input type="submit" value="Delete" class="btn btn-default" />
          </form>
        </div>
      </div>
    </div>
  </div>
  {% if forloop.counter|divisibleby:2 %}
</div>
{% endif %}
{% endfor %}
<div class="jumbotron">
  <div class="container">
    <form action="{% url 'InvoiceAdd' %}" method="GET">
      <input type="submit" value="Add New Invoice" class="btn btn-default"/>
    </form>
  </div>
</div>

invoice/templates/invoice_view.html
{% load staticfiles %}


{% include "menu.html" %}

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

<script src="{% static 'js/countInvoice.js' %}" language="Javascript" type="text/javascript"></script>
<script language="Javascript" type="text/javascript">
window.onload = function() {
  countWholeInvoice('articleList', 'sum_netto', 'sum_vat', 'sum_brutto');
};
</script>

<div class="jumbotron">
  <div class="container">

    <h2>Invoice: </h2>
    <div class="row">
      <div class="col-md-2">
        {% if Invoice.Contractor.Supplier %}
        <h3>Seller</h3>
        {% else %}
        <h3>Buyer</h3>
        {% endif %}
      </div>
      <div class="col-md-2">
        <h3>Date of Sale</h3>
      </div>
      <div class="col-md-3">
        <h3>Method of Payment</h3>
      </div>
      <div class="col-md-2">
        <h3>Date of Payment</h3>
      </div>
    </div>
    
    <div class="row">
      <div class="light">
        <div class="col-md-2">
          <p>{{ Invoice.Contractor }}</p>
        </div>
        <div class="col-md-2">
          <p>{{ Invoice.DateOfSale }}</p>
        </div>
        <div class="col-md-3">
          <p>{{ Invoice.get_MethodOfPayment_display }}</p>
        </div>
        <div class="col-md-2">
          <p>{{ Invoice.DateOfPayment }}</p>
        </div>
      </div>
    </div>
  </div>
</div>
  <div class="container">
    <h2>Articles: </h2>

    <div class="row">
      <div class="col-md-2">
        <h3>Code</h3>
      </div>
      <div class="col-md-2">
        <h3>Name</h3>
      </div>
      <div class="col-md-1">
        <h3>Price</h3>
      </div>
      <div class="col-md-2">
        <h3>Quantity</h3>
      </div>
      <div class="col-md-1">
        <h3>Netto</h3>
      </div>
      <div class="col-md-1">
        <h3>VAT</h3>
      </div>
      <div class="col-md-1">
        <h3>Brutto</h3>
      </div>
    </div>

    <div class="light" id="articleList">
      {% for ArticleGatherer in ArticleGatherers %}
      <div class="row" id="{{ ArticleGatherer.pk }}">
        <div class="col-md-2">
          <h3>{{ ArticleGatherer.Article.Code }}</h3>
        </div>
        <div class="col-md-2">
          <h3>{{ ArticleGatherer.Article.Name }}</h3>
        </div>
        <div class="col-md-1">
          <h3 id="{{ ArticleGatherer.pk  }}_price">{{ ArticleGatherer.Article.Price }}</h3>
        </div>
        <div class="col-md-2">
          <h3 id="{{ ArticleGatherer.pk  }}_quantity">{{ ArticleGatherer.Quantity }}</h3>
        </div>
        <div class="col-md-1">
          <h3 id="{{ ArticleGatherer.pk  }}_netto">Netto</h3>
        </div>
        <div class="col-md-1">
          <h3 id="{{ ArticleGatherer.pk  }}_vat">VAT</h3>
        </div>
        <div class="col-md-1">
          <h3 id="{{ ArticleGatherer.pk  }}_brutto">Brutto</h3>
        </div>
      </div>
      {% endfor  %}
    </div>
</div>
<div class="jumbotron">
  <div class="container">
    <h2>Summary: </h2>

    <div class="row">
      <div class="col-md-2">
        <h3>Netto</h3>
      </div>
      <div class="col-md-3">
        <h3>VAT</h3>
      </div>
      <div class="col-md-2">
        <h3>Brutto</h3>
      </div>
    </div>

    <div class="row">
      <div class="light">
        <div class="col-md-2">
          <h3 id="sum_netto">Netto</h3>
        </div>
        <div class="col-md-3">
          <h3 id="sum_vat">VAT</h3>
        </div>
        <div class="col-md-2">
          <h3 id="sum_brutto">Brutto</h3>
      </div>
      </div>
    </div>

  </div>
</div>